name: Jekyll Transclude Prototype
baseurl: /jekyll-transclude

exclude: ["excluded_folder", "Rakefile"]

plugins:
  - ./_plugins/jekyll-transclude

copy_files_plugin:
  to_dir: './_site/assets/js'
  from_files:
    - './excluded_folder/test.js'